"""Create listings table

Revision ID: 62b16f27f039
Revises: 
Create Date: 2025-11-28 11:56:31.864682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62b16f27f039'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(length=255), nullable=False),
    sa.Column('source_plugin_id', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=255), nullable=False),
    sa.Column('source_original_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=10), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_score', 'listings', ['fraud_score'], unique=False)
    op.create_index('idx_location_city_type', 'listings', ['location_city', 'type'], unique=False)
    op.create_index('idx_location_coordinates', 'listings', ['location_lat', 'location_lng'], unique=False, postgresql_using='btree')
    op.create_index('idx_price_range', 'listings', ['price_amount'], unique=False)
    op.create_index(op.f('ix_listings_fraud_score'), 'listings', ['fraud_score'], unique=False)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_listing_id'), 'listings', ['listing_id'], unique=True)
    op.create_index(op.f('ix_listings_location_city'), 'listings', ['location_city'], unique=False)
    op.create_index(op.f('ix_listings_price_amount'), 'listings', ['price_amount'], unique=False)
    op.create_index(op.f('ix_listings_property_type'), 'listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_listings_source_plugin_id'), 'listings', ['source_plugin_id'], unique=False)
    op.create_index(op.f('ix_listings_type'), 'listings', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_plugin_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_property_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_price_amount'), table_name='listings')
    op.drop_index(op.f('ix_listings_location_city'), table_name='listings')
    op.drop_index(op.f('ix_listings_listing_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_fraud_score'), table_name='listings')
    op.drop_index('idx_price_range', table_name='listings')
    op.drop_index('idx_location_coordinates', table_name='listings', postgresql_using='btree')
    op.drop_index('idx_location_city_type', table_name='listings')
    op.drop_index('idx_fraud_score', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
